-- 各種テーブル削除
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

--ユーザーテーブル
CREATE TABLE users
(
user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email VARCHAR(255),
name  VARCHAR(20),
password VARCHAR(255)
);

--カテゴリーテーブル
CREATE TABLE categories
(
category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(20)
);

-- タスクテーブル
CREATE TABLE tasks
(
task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id INTEGER,
category_id INTEGER,
date_now DATE,
name VARCHAR(20),
title VARCHAR(255),
closing_date DATE,
progress INTEGER,
memo TEXT,
FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE CASCADE
);